uploads = []
outputs = []

[[generated]]
id = "CeZDPOrSwXYPmaUiwNGEI"
uri = "file://frontend/public/project-academy.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Zd7ik5M9FlX_-_O-jeVZm"
uri = "file://frontend/public/project-caravana.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Z_zjWVjxQuaEuYKs9d0Hf"
uri = "file://frontend/public/project-playbooks.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DlCxqK2_f5FqS_fw9Nyn0"
uri = "file://frontend/public/project-pawsitive.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5GPo8XsrrUA2Z8unVJHgu"
uri = "file://frontend/public/project-calea-victoriei.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sj9ib8p3DWgXAWj4TAddB"
uri = "file://frontend/public/gallery-phone-mockup.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QWR8DC4uX-A3uerB8WFCw"
uri = "file://frontend/public/gallery-video-mapping.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ECynPzH9W6GYnzzGAW-OV"
uri = "file://frontend/public/gallery-classroom.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cxbvii1ApRR5zkSN8eDe5"
uri = "file://frontend/public/gallery-amphitheater.png"
type = "image"
title = "generated_image"

[[generated]]
id = "A_fj_tvNDv-oda3WyGZT7"
uri = "file://frontend/public/gallery-robot-park.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JwkbtqM1gcWm1loo5BbWu"
uri = "file://frontend/public/gallery-ar-museum.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1L39OF8hXZUIrv4Lf6sGV"
uri = "file://frontend/public/gallery-interactive-museum.png"
type = "image"
title = "generated_image"
